---

###
### Asserts
###

# Assert that required name element is present
- name: ensure security_groups[x].security_group contains name key
  assert:
    that:
      - sg.name is defined
      - sg.name | length > 0
    msg: "aws_ec2_security_groups[x].security_group[y].name not defined, but required"

- name: ensure rules are defined correctly
  assert:
    that:
      # Protocol must be present
      - item.proto is defined
      # Ports must be present
      - item.ports is defined
      # cidrv4 and/or group_id and/or cidr_ipv6 and/or group_name and/or rule_desc Must be present
      # According to https://docs.ansible.com/ansible/latest/modules/ec2_group_module.html#parameter-rules
      - item.cidr_ip is defined or item.group_name is defined or item.group_id is defined or item.cidr_ipv6 or
        item.rule_desc is defined
    msg: "aws_ec2_security_groups[x].rules[y] is not defined correctly"
  with_items:
    - "{{ lookup('flattened', sg.rules) }}"

###
### Gather resources
###

# Returns:
# * aws_ec2_security_group_vpc_id
- include_tasks: gather_facts_vpc_by_filter.yml
  when:
    - sg.vpc_filter is defined

# Returns:
# * aws_ec2_security_group_vpc_id
- include_tasks: gather_facts_vpc_by_name.yml
  when:
    - sg.vpc_name is defined

- name: set sg tags
  set_fact:
    _aws_ec2_security_group_tags: |
      {{
        sg.tags | default([]) + [{
          'key': 'Name',
          'val': sg.name
        }]
      }}

- name: "ensure securty group is created: {{ sg.name }}"
  ec2_group:
    # Fixed Values
    state: present
    # Dynamic Values
    name: "{{ sg.name }}"
    description: "{{ sg.name }}"
    rules: "{{ sg.rules | default(omit) }}"
    # Looked-up Values
    vpc_id: "{{ aws_ec2_security_group_vpc_id }}"
    # Optional Values
    tags: "{{ _aws_ec2_security_group_tags | get_attr('key', 'val') }}"
    region: "{{ sg.region | default(aws_ec2_security_group_default_region | default(omit)) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_access_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit) }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_ec2_security_group_profile | default(omit) }}"
