---

- name: combine vpc filter
  set_fact:
    _aws_ec2_security_group_vpc_filter: |
      {{
        aws_ec2_security_group_vpc_filter_additional + ec2.vpc_filter
      }}

- name: gather vpc facts by filter
  ec2_vpc_net_facts:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') | default(omit)  }}"
    security_token: "{{ lookup('env', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_ec2_security_group_profile | default(omit) }}"
    region: "{{ ec2.region | default(aws_ec2_security_group_default_region) }}"
    filters: "{{ _aws_ec2_security_group_vpc_filter | get_attr('key', 'val') }}"
  register: _ec2_sg_vpc

- name: fail if vpc was not found
  assert:
    that:
      - _ec2_sg_vpc.vpcs is defined
      - _ec2_sg_vpc.vpcs | length == 1
    msg: Not exactly one VPC has been found

- name: set vpc id
  set_fact:
    aws_ec2_security_group_vpc_id: "{{ _ec2_sg_vpc.vpcs[0].id }}"
